#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

PATH1='/projectnb2/bf528/project_2/reference/'
PATH2='/projectnb/bf528/users/saxophone/project2/'

#1. Load all modules (include python2 because python version issue with tophat)
module load python2 samtools/0.1.19 bowtie2 boost tophat

#2. Run tophat to align the two FASTQ files against mm9 reference
tophat -p 16 -r 200 --segment-mismatches=1 --segment-length=20 --no-novel-juncs -G $PATH1'annot/mm9.gtf' -o $PATH2'scripts/programmer/P0_1_tophat' $PATH1'mm9' $PATH2'samples/P0_1_1.fastq' $PATH2'samples/P0_1_2.fastq'  

echo "Job finished: $(date +%F)"
